# INCLUDE CLIENT PORT IF NOT 80/443!
frontend: http://localhost:3000
backend: http://localhost:4000

port: 4000

db: mongodb://wiki-mongodb:27017/wiki
search: wiki-es01:9200

paths:
  repo: ./repo
  data: ./data

uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100

auth:
  local:
    defaultAdminEmail: admin@admin.com

sessionSecret: skjdfz21asiefkasgz213saeifdkhasjk123fhskaje

git:
  url: https://gitlab.com/JohnMcClan3/camelotwikidata
  branch: master
  auth:
    # Type: basic or ssh
    type: basic
    # Only for Basic authentication:
    username:
    password:

externalLogging:
  papertrail:
    active: false
    host: logs4.papertrailapp.com
    port: 53072
    level: info
