version: '3'
services:
  wiki-mongo:
    container_name: wiki-mongodb
    image: mongo
    restart: always
    volumes:
      - /home/tpoe/Dev/wiki/data:/data/db
    networks:
      - backend
  wiki-server:
    container_name: wiki-server
    build: ./wiki-server
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - wiki-mongo
    volumes:
      - ./wiki-server/config.yml:/var/wiki/config.yml
      - ./wiki-server/repo:/var/wiki/repo:rw
    networks:
      - elasticsearch_esnet
      - backend
  wiki-app:
    container_name: wiki-app
    build:
      context: ./wiki-app
      args:
        env: prod
    restart: always
    ports:
      - 3000:3000

networks: 
  backend:
  elasticsearch_esnet:
    external: true