name: Wiki.js
defaults:
  config:
    title: Wiki
    host: http://localhost
    listenAddress: 0.0.0.0
    port: 80
    paths:
      repo: ./repo
      data: ./data
    uploads:
      maxImageFileSize: 3,
      maxOtherFileSize: 100
    auth:
      defaultAdminEmail: admin@admin.com
    lang: en
    langRtl: false
    public: false
    db: mongodb://localhost/wiki
    sessionSecret: null
    admin: null
    git:
      url: null
      branch: master
      auth:
        type: basic
        username: null
        password: null
        privateKey: null
        sslVerify: true
      serverEmail: wiki@example.com
      showUserEmail: true
    features:
      linebreaks: true
      mathjax: true
    externalLogging:
      bugsnap: false
      loggly: false
      papertrail: false
      rollbar: false
      sentry: false
    theme:
      primary: indigo
      alt: blue-grey
      footer: blue-grey
      viewSource: false
      code:
        dark: true
        colorize: true
