version: '3.7'
services:
  wiki-app:
    container_name: wiki-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      API_URL: http://localhost:4000
